### ISSUE TITLE
Facebook.Likes.Count and Facebook.Comments.Count are always returning 0

### ISSUE THREAD

**Issue by joshua-stewart** [abjerner/Skybrud.Social#34] opened 2015-07-16 20:01 UTC
In 0.9.3 FacebookPost.Likes.Count and FacebookPost.Comments.Count are returning 0

The FacekbookLikes call and the FacebookComments calls are trying to parse the "count" property the same way you changed Shares to work in 0.9.3 using:

Count = obj.GetInt32("count") 

but neither Likes or Shares have a "count" property in the JsonObject so they are both returning 0.

**Comment by abjerner** [comment] 2015-07-16 20:54
Thanks for reporting :D

I can't remember this exactly, but then Facebook might have changed something. I will look into it, and create a fix for the next release if necessary ;)

**Comment by joshua-stewart** [comment] 2015-07-16 20:59
Thanks for the quick response - I appreciate it. 

I did a bit of digging and it looks like to get the counts for Likes and Comments you have to set the summary flag to true and then they comeback with a summary element and property of total_count

You can test it by using these URLs: 

https://graph.facebook.com/POST_ID/likes?summary=true&access_token=XXXXXXXXXXXX

https://graph.facebook.com/POST_ID/comments?summary=true&access_token=XXXXXXXXXXXX

Thanks again.

**Comment by joshua-stewart** [comment] 2015-07-17 15:01
I did some more research and it appears there isn't a way to specify summary=true when pulling all posts unless you specify which fields you want. So in order to return the counts for Likes and Comments you can either build a query that specifies all the fields and add .summary(true) to the likes and comments fields or make a separate call like the one below to return just the Likes and Comments total_counts and merge the 2 data sets:

https://graph.facebook.com/PAGE_ID/posts?fields=comments.limit(0).summary(true),likes.limit(0).summary(true)&limit=20&access_token=XXXXXXXXXXXX

I can't see how you would be able to do this from within Skybrud unless you change a lot of the plumbing, but hopefully I'm wrong.

**Comment by abjerner** [comment] 2015-07-17 15:59
Looking a bit further into the matter, it still seems that Facebook has changed something in their API - also for some of the older API versions (Skybrud.Social uses v2.2 by default). I'm pretty sure the comment count and like count was exposed by default when I wrote the code.

Anyways, I think you're right regarding having to specify which fields that should be returned. This becomes even more necessary when you read [this news post](https://developers.facebook.com/blog/post/2015/07/08/graph-api-v2.4/) by Facebook. v2.4 will have "Fewer default fields for faster performance". Google are already doing something similar for the YouTube API, although not as complex.

I think for the next release, I will add support for specifying a `Fields` property (as a string for now):

```C#
// Make the request to the API
FacebookPostsResponse response = service.Posts.GetPosts("me", new FacebookPostsOptions {
    Fields = "comments.limit(0).summary(true),likes.limit(0).summary(true)",
    Limit = 20
});
```

And then for next release after that, perhaps add some utility methods for helping developers to generate the fields string (since it can be become quite complex as you have pointed out).

**Comment by joshua-stewart** [comment] 2015-07-21 16:53
Thank for the update. Sounds great.

**Comment by abjerner** [comment] 2015-08-11 19:13
Moving this to `v0.9.4.1` to speed up the release of `v0.9.4`. Hoping to release `v0.9.4.1` soon though ;)

**Comment by abjerner** [comment] 2015-08-14 16:37
Just a little update:

As of `v0.9.4.1`, this is now supported for most endpoints - including the `Posts` endpoint.

To specify the fields to be returned, you can now do something like:

```C#
// Declare the options for the call to the API
FacebookGetPostsOptions options = new FacebookGetPostsOptions {
    Identifier = "skybrud",
    Fields = new [] { "id", "name", "from", "message" }
};

// Make the call to the API
FacebookPostsResponse response = service.Posts.GetPosts(options);
```

Notice that the `FacebookGetPostsOptions` now replaces the `FacebookPostsOptions` class. `FacebookPostsOptions` can still be used, but is marked as obsolete.

I will try to update the remaining endpoints for `v0.9.4.2`.

**Comment by AndersBrohus** [comment] 2016-02-05 09:22
Hi @abjerner :-)

This bug i still there.. :-(

**Comment by abjerner** [comment] 2016-02-05 09:26
@AndersBrohus If I remember correctly, it depends on the parameters/options you specify for the call to the API. But if you can provide an example of your code, I'll have a look at it when I have some time ;)

**Comment by AndersBrohus** [comment] 2016-02-05 09:30
I tried with this code :-)    

```
public FacebookPostsResponse getFBAccess()
        {

            string appId = "XXXXXXX";
            string appSecret = "XXXXXXXXXXXXXXXXXXXXX";

            FacebookOAuthClient client = new FacebookOAuthClient(appId, appSecret);
            string accessToken = client.GetAppAccessToken();

            FacebookService service = FacebookService.CreateFromAccessToken(accessToken);

            FacebookPostsResponse response = service.Posts.GetPosts("XXXXXXXXXXXXXX");

            return response;
        }
```

The X's definded to the real strings and ids :P

**Comment by abjerner** [comment] 2016-02-05 16:17
@AndersBrohus Based on your code, I'm not exactly sure what you're trying to do? Are you trying to get the amount of likes/comments of each individual post?

If so, this is not directly supported at the moment. For a given post, `post.Likes.Count` will now always be `0` since Facebook doesn't specify the count this way anymore.

While not directly supported, you can still accomplish it by playing around with the underlying JSON:

```
FacebookPostsResponse response = service.Posts.GetPosts(new FacebookGetPostsOptions {
    Identifier = "skybrud",
    Fields = new[] {
        // add more fields if you need them
        "comments.limit(0).summary(true)",
        "likes.limit(0).summary(true)"
    }
});

foreach (FacebookPost post in response.Body.Data) {
        
    int likes = post.Likes.JsonObject.GetObject("summary").GetInt32("total_count");
    int comments = post.Comments.JsonObject.GetObject("summary").GetInt32("total_count");

}
```

The first thing you should notice in the example above, is that you have to explicitly tell the Graph API to return the total count for both likes and comments. Then you can read the total count through the JSON as shown.

I will look into adding properties for this to the next release. If you meant something totally different, just give me a shout back, and we'll take it from there ;)

**Comment by AndersBrohus** [comment] 2016-02-08 07:28
Hi again @abjerner :-)

The code i posted is the way i call the API, and in the response there is a "total count" of likes and comments that always says 0 :-)

**Comment by abjerner** [comment] 2016-02-08 07:54
@AndersBrohus Can you post an example of the part of your code that actually reads the total count? You may have to do it as in my example since Facebook changed the way they specify the total count.

**Comment by AndersBrohus** [comment] 2016-02-08 08:04
@abjerner I don't need the total count, i just returned the response that i got with the code from above :-)

**Comment by abjerner** [comment] 2016-02-08 08:33
@AndersBrohus Then I'm not sure what the issue is?

**Comment by AndersBrohus** [comment] 2016-02-08 08:52
The issue is, when you make a call like this

```
            string appId = "Your App Id";
            string appSecret = "Your App Secret";

            FacebookOAuthClient client = new FacebookOAuthClient(appId, appSecret);
            string accessToken = client.GetAppAccessToken();

            FacebookService service = FacebookService.CreateFromAccessToken(accessToken);
            FacebookPostsResponse response = service.Posts.GetPosts("Your FB Page Id");

            return response;
```

Then the response, has these two section for each post,

"Likes": {
          "Count": 0,
          "Data": [{
              "Id": "10153901520163088",
              "Name": "Patrick Østergård Jürgensen"
            },
            {
              "Id": "10153937673244549",
              "Name": "Kasper Hermann Due Stück"
            },]
},"Comments": {
          "Count": 0,
          "Data": [{
              "Id": "926481614114273_926759300753171",
              "From": {
                "Id": "1214661998548175",
                "Name": "Mari Carmen Molino Garrido"
              },
              "Message": "Oleeee los tios guapos!!! Enhorabuena!!!",
              "MessageTags": null,
              "CreatedTime": "2016-02-05T20:09:05+01:00",
              "Likes": 0
            },
            {
              "Id": "926481614114273_926788887416879",
              "From": {
                "Id": "846143215497081",
                "Name": "Bodil Nielsen"
              },
              "Message": "👍 👏 🤓 ✍🏻  👾  💻  ❤️",
              "MessageTags": null,
              "CreatedTime": "2016-02-05T21:44:04+01:00",
              "Likes": 0
            }]
}

But the "Count" in each section is 0,  when there are comments and likes :-)
And then i found this issue and thought they where similar :-)

**Comment by abjerner** [comment] 2016-02-08 11:46
@AndersBrohus Okay. Thanks for the heads up then ;)

The `count` property used to part of the JSON received from Facebook, which is why there is a corresponding `Count` property in Skybrud.Social. But since the property is now deprecated in the Facebook API, the property will be removed in v1.0 of Skybrud.Social as well (which instead will have support for reading the count the correct/new way).

**Comment by AndersBrohus** [comment] 2016-02-08 14:33
Heh, no problem @abjerner :-)

Sounds great! :-)

**Comment by bjarnef** [comment] 2017-02-01 21:22
@abjerner I can get likes and comments count using the following:

```
Fields = new[] {
    "full_picture,type,link,picture,name,from,message,description,permalink_url,created_time",
    // add more fields if you need them
    "comments.limit(0).summary(true)",
    "likes.limit(0).summary(true)"
}

if (post != null)
{
    int likes = post.Likes.JsonObject.GetObject("summary").GetInt32("total_count");
    int comments = post.Comments.JsonObject.GetObject("summary").GetInt32("total_count");

   @string.Format("Likes: {0}, Comments: {1}", likes, comments)
}
```

How do I handle it for shares count, since it a bit different.

```
{
  "posts": {
    "data": [
      {
        "shares": {
          "count": 4
        },
        "id": "xxx"
      },
    ]
  }
}
```

**Comment by abjerner** [comment] 2017-02-01 21:42
@bjarnef There is also a `shares` field that you can request.

If you're using `Skybrud.Social`, your example above could be updated to:

```C#
Fields = new[] {
    "full_picture,type,link,picture,name,from,message,description,permalink_url,created_time,shares",
    // add more fields if you need them
    "comments.limit(0).summary(true)",
    "likes.limit(0).summary(true)"
}

if (post != null)
{
    int likes = post.Likes.JsonObject.GetObject("summary").GetInt32("total_count");
    int comments = post.Comments.JsonObject.GetObject("summary").GetInt32("total_count");

    JsonObject sharesObj = post.JsonObject.GetObject("shares");
    int shares = sharesObj == null ? 0 : sharesObj.GetInt32("count");

   @string.Format("Likes: {0}, Comments: {1}, Shares: {1}", likes, comments, shares)
}
```

If you're using `Skybrud.Social.Core` and `Skybrud.Social.Facebook`, your code could look like this:

```C#
@using Skybrud.Social.Facebook
@using Skybrud.Social.Facebook.Objects.Posts
@using Skybrud.Social.Facebook.Options.Posts
@using Skybrud.Social.Facebook.Responses.Posts
@inherits WebViewPage<FacebookService>
              
@{

    FacebookGetPostsResponse response = Model.Posts.GetPosts(new FacebookGetPostsOptions {
        Identifier = "skybrud",
        Fields = "comments.limit(0).summary(true),likes.limit(0).summary(true),shares",
    });

    foreach (FacebookPost post in response.Body.Data) {

        <pre><strong>@post.Id</strong></pre>
        <pre>Comments: @post.Comments.Summary.TotalCount</pre>
        <pre>Likes: @post.Likes.Summary.TotalCount</pre>
        <pre>Shares: @(post.Shares == null ? 0 : post.Shares.Count)</pre>

        <hr />

    }

}
```

**Comment by bjarnef** [comment] 2017-02-01 21:53
@abjerner okay, I tried some different approaches in `Skybrud.Social` and also added the `shares` field.

I was missing this part to be correct:

```
Skybrud.Social.Json.JsonObject sharesObj = post.JsonObject.GetObject("shares");
int shares = sharesObj == null ? 0 : sharesObj.GetInt32("count");
```

**Comment by abjerner** [comment] 2018-04-28 17:52
From what I can tell, the issues reported in this thread has been part of [**Skybrud.Social.Facebook**](https://github.com/abjerner/Skybrud.Social.Facebook) for some time now, so I'm closing this old issue. Thanks all for reporting ;)

**Closed by abjerner** 2018-04-28 17:52 UTC
Labels: Facebook, bug
